### ISSUE TITLE
Enhancement for log time

### ISSUE THREAD

**Issue by clarkerz** [OpenDroneMap/NodeODM#10]
Raised as enhancement as advised: Would it be possible to allow the rolling log in the WebODM GUI to be configurable or to show System/Server Time? i.e My server is set to BST (GMT +1) but the output shows GMT or BST -1.

![faff6876-2919-11e7-974d-b565513ef967](https://cloud.githubusercontent.com/assets/9163611/25424150/3b65027c-2a5f-11e7-9302-518956e2ce6b.png)

**Comment by SachinVarghese** [comment]
@pierotofy Could you clarify the issue with relevant updates as the initial problem seems to be quite old?

**Comment by pierotofy** [comment]
Hey @SachinVarghese ✋ looking at this issue more carefully, it seems like this would be a logging problem in OpenSfM (a library we use in NodeODM), so this issue should have been opened there. I’m sure the maintainers of OpenSfM might welcome a fix (https://github.com/mapillary/OpenSfM). I will close this one for now here.
