### ISSUE TITLE
Make zipping faster/memory efficient by replacing nodejs lib with native app

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/NodeODM#106]
Zipping tends to take a lot of memory with very large datasets. We should seek to improve that by replacing the archiver library with a native call to a zip utility.

**Comment by smathermather** [comment]
I've been meaning to create this issue for a couple days. :D

**Comment by pierotofy** [comment]
Fixed in #99

**Comment by smathermather** [comment]
Fantabulous. I thank you. My massive datasets thank you.
