### ISSUE TITLE
Feature request: Including log file in downloadable assets

### ISSUE THREAD

**Issue by askeuhd** [OpenDroneMap/NodeODM#112]
I do a lot of processing on AWS Spot Instances and once I am done with them they get deleted for good - I often forget to download the logfile, which is a shame because I forget the exact settings I have used from time to time.

Would be hard or possible to include the txt logfile ind the "all.zip" downloadable asset? It should not take up that much additional space compared to the other assets in this file, and it is really helpful to at least have all the settings permanently recorded.

**Comment by pierotofy** [comment]
Wouldn't be too hard to add I think; would you be interested in making a pull request?

**Comment by hy9be** [comment]
@pierotofy Any guidance on where to start? I'm interested to make a PR for this.

**Comment by pierotofy** [comment]
I would wrap the calls to `this.output.push` (from other places in the code too) into a function and have the code push to the output array while writing to a file. Other options might be doable too.

**Comment by gubinhua** [comment]
File "/code/stages/odm_meshing.py", line 66, in process
mesh.create_25dmesh(tree.filtered_point_cloud, tree.odm_25dmesh,
File "/code/opendm/mesh.py", line 42, in create_25dmesh
mesh = screened_poisson_reconstruction(dsm_points, outMesh, depth=depth,
File "/code/opendm/mesh.py", line 162, in screened_poisson_reconstruction
system.run('{bin} --in {infile} '
File "/code/opendm/system.py", line 79, in run
raise Exception("Child returned {}".format(retcode))
Exception: Child returned 134

**Comment by pierotofy** [comment]
@gubinhua could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:

**Comment by pierotofy** [comment]
This is now implemented :clinking_glasses:
