### ISSUE TITLE
max-concurrency set to 6 still overloading 9 vProcessors

### ISSUE THREAD

**Issue by gotjoshua** [OpenDroneMap/NodeODM#116]
### What is the problem?

I have a 6core (12 v core) processor and I set a processing job to use max-concurrency: 6.
I am using docker-compose 2.3 to limit the CPUs for the node-odm service to use core #s 4-12.
The load is steadily over 15 and often spiking over 20.

### What should be the expected behavior?

I would expect that if i set max-concurrency to 6 and I have 9 cores available, then load should stay under 9-10.

### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)

Set up a big processing job and limit the cpuset in docker-compose:
```
cpus: 9                                                                                                               
cpuset: 3,4,5,6,7,8,9,10,11 
```
and set max-concurrency: 6

I assume a similar proportion will have similar effects if you have more or less cores on the test machine.

**Comment by pierotofy** [comment]
Hey @gotjoshua :hand: thanks for the report; double check the flag, it's `max_concurrency`, not `max-concurrency`?

**Comment by gotjoshua** [comment]
Hello! well, I am using web-odm to set it, so i think its correct, here is the server log (i dropped it to 4 in this attempt, and it appears to be playing nicely now):
```
 /code/run.sh --pc-classify --resize-to -
1 --orthophoto-resolution 5 --dtm --dem-resolution 10 --mesh-octree-depth 8 --sp
lit-overlap 180 --dem-decimation 8 --split 350 --dsm --dem-gapfill-steps 3 --max
-concurrency 4 --camera-lens brown --depthmap-resolution 512 --verbose --project
-path /var/www/data a51d23c1-8dfe-4c4e-9cb4-7e6bbad63f85
```

perhaps the concurrency should default to (vcores * 0.5 - 1)... As it seems that each thread is capable of up to 400% CPU in spikes, so when i had 6 threads if they spike together over 150% cpu, then they will fully saturate the 9 cores available to them and start to drive up the load.

Interesting thing is, that the process seems to even run much more quickly now, because the load is staying within reasonable ranges.

**Comment by pierotofy** [comment]
Ah, I see. I think you're seeing the number of "virtual cores" (`--max-concurrency`) refers to the number of physical cores. If you have something like hyper-threading, then max-concurrency set to `4` will use up to `8` logical cores. 

Perhaps you can achieve your desired result by setting the value to `2` instead of `4`?

**Comment by gotjoshua** [comment]
That explains it!! Thanks.
As I have 9 vCores available(for the node docker container) i think 4 is low enough for now, it seems to be running much more stably now.

Perhaps this could go as a detail into the tooltip in web-odm with a different recommendation (and even default value if possible to get system info about the number of cores available)

Cheers!
