### ISSUE TITLE
Ground Control Points

### ISSUE THREAD

**Issue by gkconsulting** [OpenDroneMap/NodeODM#12]
Hi, this is just a question. 
I noticed that the folder that the Ground Control Points are loaded into is called GPC.
I just wanted to know if this is correct (Ground Point Correction ???) or a typo?
Thanks so much

**Comment by pierotofy** [comment]
That's a typo. Nice catch!

**Comment by gkconsulting** [comment]
Thanks, did want to change it if it was correct. Will try update tonight and put in a pull request. Thanks

**Comment by pierotofy** [comment]
Do you need any help with this one @gkconsulting ?

**Comment by pierotofy** [comment]
This has been fixed some time ago.
