### ISSUE TITLE
Bad link in readme.md

### ISSUE THREAD

**Issue by kikislater** [OpenDroneMap/NodeODM#122]
### What is the problem?

one link in Readme.md is wrong 

### What should be the expected behavior?

Good link or proper redirection

### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)

Line 27 : Load some images is a wrong link. it affects NodeCM as well since this is the same base

Which link should it be ? May be https://github.com/OpenDroneMap/ODMdata

**Comment by pierotofy** [comment]
Hey @kikislater  :hand: would you be interested in opening a PR to fix this?

**Comment by kikislater** [comment]
Yep if link mentioned is the proper one
