### ISSUE TITLE
Docker Versioning

### ISSUE THREAD

**Issue by bitshiftza** [OpenDroneMap/NodeODM#130]
### What is the problem?

New docker images are always tagged as `latest`. This means there's no way of ensuring that you get the same docker image each time you run `docker pull`.

### What should be the expected behavior?

1. The newest image is tagged with `latest` for those who want the absolute latest version.
2. Each time a new version of the image is pushed, also tag it with a version number. This would be especially useful when deploying NodeODM across multiple servers to ensure they're all running the exact same version.

**Comment by pierotofy** [comment]
Docker lets you re-tag images, (see `docker tag`), so one could pin a specific version if they want to. We are on a rolling-release https://en.wikipedia.org/wiki/Rolling_release deployment strategy. Especially with the new changes coming to docker https://www.docker.com/pricing/resource-consumption-updates we're probably not going to offer versioning, even for ODM (which we currently tag).
