### ISSUE TITLE
when i ues nodeDOM or opendronemap  to create orthophoto, crashed

### ISSUE THREAD

**Issue by gubinhua** [OpenDroneMap/NodeODM#142]
when i ues nodeDOM to create orthophoto , this problem pop up. I don't know why and how to fixed it 

File "/code/stages/odm_meshing.py", line 66, in process
mesh.create_25dmesh(tree.filtered_point_cloud, tree.odm_25dmesh,
File "/code/opendm/mesh.py", line 42, in create_25dmesh
mesh = screened_poisson_reconstruction(dsm_points, outMesh, depth=depth,
File "/code/opendm/mesh.py", line 162, in screened_poisson_reconstruction
system.run('{bin} --in {infile} '
File "/code/opendm/system.py", line 79, in run
raise Exception("Child returned {}".format(retcode))
Exception: Child returned 134

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
