### ISSUE TITLE
Lack of CORS support causing failures

### ISSUE THREAD

**Issue by recoiladam** [OpenDroneMap/NodeODM#146]
### What is the problem?

CORS (Cross-Origin Resource Sharing) does not exist. When I make a `POST` request to `/task/new/init?token=` using `axios`, the OPTIONS request fails and the subsequent `POST` request fails because CORS support does not exist. Within axios, there is no way to disable the CORS requests. 

### What should be the expected behavior?

CORS OPTIONS requests should be successful.

### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)

```
        axios.post('/task/new/init?token=', formTask, {
          headers: {
            'set-uuid': uuid
          }
        }).then((response) => {
          console.log("NodeODM Response: ", response)
        }).catch((error) => {
          console.log("NodeODM Task Creation Error", error)
        })
```

It should be pretty simple to add CORS support using https://www.npmjs.com/package/cors which is what I am using in my own API. I have thought about putting NodeODM behind an NGINX proxy to enable CORS support but have not taken the time to write the NGINX reverse proxy configuration. It would be nice to just have CORS support directly in NodeODM so that a reverse proxy is not needed.

**Comment by pierotofy** [comment]
Hey @recoiladam sounds like a useful addition. Interested in contributing a PR for this?

**Comment by recoiladam** [comment]
I have never committed to a public project but sure, I can give it a shot.

**Comment by recoiladam** [comment]
Pull request #147 created. I hope I did that correctly.

**Comment by pierotofy** [comment]
You did! :) Welcome to the community.
