### ISSUE TITLE
GPU processing inside NodeODM

### ISSUE THREAD

**Issue by markFieldman** [OpenDroneMap/NodeODM#150]
### What is the problem?
Support of GPU in NodeODM with using another base image at Dockerfile, or with additional Dockerfile.
As I see, that GPU support was recently published. https://github.com/OpenDroneMap/ODM/issues/92
I created my own version of NodeODM with replaced base image, and it works incredibly fast!!
![Results](https://user-images.githubusercontent.com/35110941/117774705-737ba200-b242-11eb-90ef-2012b7455611.png)
Can we add it into main repository? If so, I will open a PR later.

**Comment by pierotofy** [comment]
Yes a PR would be most welcome!

**Comment by markFieldman** [comment]
> Yes a PR would be most welcome!

Done https://github.com/OpenDroneMap/NodeODM/pull/151
