### ISSUE TITLE
Tiles compression using WebP, instead of PNG tiles. Using WebP (optionally) as input format for overall process.

### ISSUE THREAD

**Issue by markFieldman** [OpenDroneMap/NodeODM#152]
### What is the problem?
PNG tiles, after generating ortophotos - was so huge, so i found my own way of tiles compression. Using [Imaginary](https://github.com/h2non/imaginary) i achieved ~10x compression (200 mb --> 20 mb) of PNG tiles to WebP tiles without image quality loss. 

### Example 1: 
PNG with size of 157kb
![PNG tile without compression](https://user-images.githubusercontent.com/35110941/118960291-ce607800-b96b-11eb-9fc2-8b2d7ffb44d9.png)
WEBP tile with compression level 70% and file size 15.2kb
![WEBP tile with compression level 70%](https://i.postimg.cc/NMxb8v71/672716.webp)

### Example 2:
PNG map zipped size = 243mb:
![image](https://user-images.githubusercontent.com/35110941/118960749-462ea280-b96c-11eb-88bf-867a7195c59a.png)
WebP map non zipped size = 24 mb:
![image](https://user-images.githubusercontent.com/35110941/118960799-5050a100-b96c-11eb-93ab-1f5044bc3e8e.png)

After this step I tried to use WebP as input for ODM. In case if file named as `<filename>.PNG` I can pass JPG or WebP as input, but cannot use `<filename>.webp`.
So i compress my dataset for processing ~5Gb from PNG to ~260mb

## Input PNG 15.6mb
[![DJI-0169.jpg](https://i.postimg.cc/g2QhxzQx/DJI-0169.jpg)](https://postimg.cc/hX8vwBSn)

## Compressed WebP 2.6mb
[![file-3.webp](https://i.postimg.cc/T1Bxrs6J/file-3.webp)](https://postimg.cc/CnC90mdR)

## Partially result of using WebP instead of PNG as input.
For using WEBP as input, i just convert it to WebP, and renamed from <filename>.webp to <filename>.png, and it works!
Result:
![Screenshot](https://user-images.githubusercontent.com/35110941/118961602-26e44500-b96d-11eb-80ea-a8a695e20747.png)

### What should be the expected behavior?
Using optional parameter for NodeODM - `Compress to tiles to WebP`. and `Use WebP as input`

**Comment by Saijin-Naib** [comment]
AVIF would also be amazing to test out as well, as it tends to compress better than WebP in most cases, and with better fidelity.

**Comment by markFieldman** [comment]
> AVIF would also be amazing to test out as well, as it tends to compress better than WebP in most cases, and with better fidelity.
> 
> https://www.ctrl.blog/entry/webp-avif-comparison.html

Main problem is browser support: 
https://caniuse.com/webp
vs 
https://caniuse.com/?search=avif

**Comment by Saijin-Naib** [comment]
> > AVIF would also be amazing to test out as well, as it tends to compress better than WebP in most cases, and with better fidelity.
> > 
> > https://www.ctrl.blog/entry/webp-avif-comparison.html
> 
> Main problem is browser support: 
> https://caniuse.com/webp
> vs 
> https://caniuse.com/?search=avif

It's certainly more forward looking, but I think it'd be great as an additional option alongside WebP.

**Comment by tteke** [comment]
For a while a go I switched form using seperately generated tiles to Cloud Optimized Geotiff's (which NodeODM generates as well). With a frontend library like geotiffjs, you can use them as if you have seperate files for each tiles. You should check it out.

**Comment by pierotofy** [comment]
Closing as COGs are probably the better way to do tiling these days (as it's been pointed out).
