### ISSUE TITLE
Interpolation method

### ISSUE THREAD

**Issue by Marklar1983** [OpenDroneMap/NodeODM#16]
G'day Guys,

Love the work you are doing! not an issue but a suggestion, would it be possible to add bicublic interpolation as a method for the DEM, DSM, 3D Mesh and Orthomosaic creation??

and are you guys leveraging GDAL in this project??

**Comment by pierotofy** [comment]
Hi @Marklar1983,

yes we are leveraging GDAL for OpenDroneMap; this would be a request to be added in this repository https://github.com/OpenDroneMap/OpenDroneMap, since node-OpenDroneMap only deals with exposing a public API for OpenDroneMap.

Good suggestion!

**Comment by pierotofy** [comment]
This belong to the ODM repo and should have been closed time ago. :+1:
