### ISSUE TITLE
Restarting a task loses --pc-ept and --cog when skipPostProcessing is not set

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/NodeODM#161]
Restarting a task will result in `--pc-ept` and `--cog` not being set if `skipPostProcessing` is not set. This is incorrect.

**Comment by matanPercepto** [comment]
Was looking at this issue and I find it the other-way around- every time I start a task, it automatically adds the --pc-ept and --cog options, even if I didn't use them (working with pyodm)
