### ISSUE TITLE
opendronemap/nodeodm:gpu referenced in docs does not exist

### ISSUE THREAD

**Issue by mikegreen** [OpenDroneMap/NodeODM#164]
### What is the problem?

In the docs, `opendronemap/nodeodm:gpu` is referenced to use for GPU support, here: 
https://github.com/OpenDroneMap/NodeODM#using-gpu-acceleration-for-sift-processing-inside-nodeodm

It appears https://hub.docker.com/r/opendronemap/nodeodm does not have a `gpu` tagged image?

### What should be the expected behavior?

opendronemap/nodeodm:gpu exists

### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)

```
$ docker run -p 3000:3000 --gpus all opendronemap/nodeodm:gpu
Unable to find image 'opendronemap/nodeodm:gpu' locally
docker: Error response from daemon: manifest for opendronemap/nodeodm:gpu not found: manifest unknown: manifest unknown.
```

**Comment by PArch** [comment]
+1

**Comment by mikegreen** [comment]
@markFieldman looks like you added this GPU doc. Can you clarify where it came from/does it currently exist?

**Comment by markFieldman** [comment]
It was added during my experiments. I forgot to add issue about creating CI pipeline for building image with GPU support.

**Comment by markFieldman** [comment]
@pierotofy can you include Dockerfile.gpu to Docker Hub CI pipeline?

**Comment by pierotofy** [comment]
I'm in the process of waiting for the docker team to approve our open source application to access the automated build feature once again (it is a paid feature now).

**Comment by pierotofy** [comment]
In the meanwhile, I've manually setup a dispatch mechanism to trigger builds via GitHub, so this should be solved! :pray:
