### ISSUE TITLE
Invalid UUID error on /task/new request with 'zipurl' param

### ISSUE THREAD

**Issue by Eragoo** [OpenDroneMap/NodeODM#177]
### What is the problem?
POST request on /task/new with zipurl throw {"error": "Invalid UUID"} error.

### What should be the expected behavior?

UUID of created task expected as response

### How reproduce this?

To reproduce with postman:

1. Specify POST request to localhost:3000/task/new
2. Make sure that Content-Type header is set to 'multipart/form-data'
3. Add body with key 'zipurl' and value 'https://github.com/Eragoo/zip-test/blob/main/Archive.zip'
<img width="850" alt="Screenshot 2022-01-21 at 14 02 21" src="https://user-images.githubusercontent.com/37846731/150523936-ca5f37e7-5be2-4774-8b24-72ca9f4592b6.png">

<img width="854" alt="Screenshot 2022-01-21 at 14 02 51" src="https://user-images.githubusercontent.com/37846731/150524006-6cf238ac-96cf-4787-a091-350d151f7366.png">

**Comment by Eragoo** [comment]
Tried to provide UUID through **set-uuid** header according to documentation but nothing changed. 

Seems like error throws from [newTask.js](https://github.com/OpenDroneMap/NodeODM/blob/bb8b7bda5cf81c649574b96c8c1237864a25872e/libs/taskNew.js) file 392 line.

**Comment by timii111** [comment]
I also got this issue with the latest version. I changed back the Docker image version to 2.4.10, that solved me the issue.
(One of my college used the image successfully last summer, that's why I chose this version)

**Comment by kauly** [comment]
I'm getting the same error with the latest gpu image
