### ISSUE TITLE
Loading dataset from: /var/www/data/552fda05-b488-4661-83d0-05733bdf343b/images

### ISSUE THREAD

**Issue by zhang7249** [OpenDroneMap/NodeODM#180]
****************************************
PLEASE REMOVE THIS NOTE AFTER READING IT!

First of all, thank you for taking the time to report an issue.

For questions, comments and feature requests, please open a topic on https://community.opendronemap.org/. This is not the right place.

Please open an issue only to report faults and bugs and follow the format specified below.
****************************************

### What is the problem?

[Type answer here]

### What should be the expected behavior?

[Type answer here]

### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)

[Type answer here]

**Comment by zhang7249** [comment]
[INFO]    use_3dmesh: False
[INFO]    use_exif: False
[INFO]    use_fixed_camera_params: False
[INFO]    use_hybrid_bundle_adjustment: False
[INFO]    verbose: False
[INFO]    ==============
[INFO]    Running dataset stage
[INFO]    Loading dataset from: /var/www/data/552fda05-b488-4661-83d0-05733bdf343b/images
[ERROR]   Not enough supported images in /var/www/data/552fda05-b488-4661-83d0-05733bdf343b/images

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
