### ISSUE TITLE
"rerun" argument does not work on nodeODM when running from pyODM

### ISSUE THREAD

**Issue by matanPercepto** [OpenDroneMap/NodeODM#182]
### What is the problem?

When starting a task with "rerun" option, this flag isn't set and the entire flow runs

### What should be the expected behavior?

the flow should only run the required stage, and not the entire flow
### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)

using pyodm:

from pyodm import Node
images = [<path_to_images>]
options = {"rerun": "opensfm"} # it has been trued with other stages too
n = Node("localhost", 3000)
t = n.create_task(images, options)

**Comment by pierotofy** [comment]
Hi @matanPercepto :hand: this is not exactly bug, it was designed this way; NodeODM cannot run a single stage at a time, but it can restart from a stage using the `rerun-from` option. See https://github.com/OpenDroneMap/NodeODM/blob/d80ec213c6f875dc263e4fc5e9c336e2f98e23a2/libs/odmInfo.js#L83 for a full list of options that will not work with NodeODM.

What's your use case? What are you building?

**Comment by matanPercepto** [comment]
Hi @pierotofy, thanks for the quick response!
I saw this line of skipped options in the code (some of them are different than the official ODM documentation options), and wanted to ask why is that?
Specifically, I am trying to run opensfm and openmvs at different stage of a project, as well as the full flow on another batch of images.
