### ISSUE TITLE
nodeodm-windows-x64.zip Missing libraries?

### ISSUE THREAD

**Issue by 6monkeyrs** [OpenDroneMap/NodeODM#188]
### What is the problem?

Missing libraries?
Windows NodeODM: https://github.com/OpenDroneMap/NodeODM/releases/latest

### What should be the expected behavior?

The nodeODM references to "F:\vm35\nodeodm0\libs\taskNew.js:305" and "libs" does not exsist in the download package.

### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)

Download the zip package, and run it within a cluster in split/merge load balance in windows. not docker version.

**Comment by pierotofy** [comment]
This is because the file in question is packed within the executable (`nodeodm.exe`) and extracted at runtime before use.
