### ISSUE TITLE
Add apptainer def file to allow HPC optimized containers

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/NodeODM#190]
### What is the problem?

Not a problem, but a feature request

### What should be the expected behavior?

Add apptainer config file to allow HPC optimized containers
### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)

NA

**Comment by smathermather** [comment]
@pierotofy -- Tested this today with a colleagues here at the college, so expect a pull request. That said, in my mind the apptainer def file should always be ported from the dockerfile, in which case we might need to set up a github action.

**Comment by nghi01** [comment]
The definition file is uploaded. I also add some basic instructions on how to build and run Apptainer in the README. Would you mind linking the pull request to this issue? https://github.com/OpenDroneMap/NodeODM/pull/191
