### ISSUE TITLE
Adding the porting of Dockerfile to Apptainer def file to the workflow

### ISSUE THREAD

**Issue by nghi01** [OpenDroneMap/NodeODM#192]
### What is the problem?
Adding the porting part of Dockerfile to apptainer definition file into the yaml workflow.

### What should be the expected behavior?
On push, the repo is going to automatically port the Dockerfile to an apptainer definition file through spython command. 

### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)
It's a feature request.

**Comment by nghi01** [comment]
I was thinking of adding a step into the publish-docker.yaml file. Or add it to publish-build-action@v3 (for example). Can anyone recommend a way to proceed?

**Comment by smathermather** [comment]
@pierotofy -- what's the best way to do this. Currently its a single python command to convert between formats, but I think we are interested in not letting the apptainer version rot as the dockerfile gets updated.

**Comment by pierotofy** [comment]
One could get fancy and write a conditional action that looks for changes on the Dockerfile (I'm sure there's a way, somehow, to get this done on GitHub), but to be honest, the Dockerfile does not change that often, and you can't trust your GitHub actions anyway (you will end up troubleshooting them as time goes on).

Or just manually update it when/if it breaks.

**Comment by smathermather** [comment]
I suppose setting up an action just changes where the bit-rot happens... . Ok. We'll just leave this as is and add a comment in the README on how to convert the dockerfile if needed.

**Comment by smathermather** [comment]
Closed by https://github.com/OpenDroneMap/NodeODM/pull/195
