### ISSUE TITLE
Feature request: Return meshes from split merge

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/NodeODM#199]
Per https://community.opendronemap.org/t/offer-a-single-textured-mesh-as-output-in-split-merge-processes/14608 , long term, returning a mesh from split merge would be beneficial. In the interim, returning the meshes that are produced may be an acceptable alternative.

I'll be taking this on, so any bread-crumbs for implementation appreciated.

**Comment by pierotofy** [comment]
I think this would be more easily implemented in ODM; at the merge stage, recursively make symlinks (or hardlinks on Windows) to the root `odm_texturing` folder, which will then be included by NodeODM.

**Comment by smathermather** [comment]
Ah, that explains a mechanism I was confused about. Cool. I'm going to open a sibling issue on the ODM repo and proceed.

**Comment by pierotofy** [comment]
Closing in favor of the ODM issue.
