### ISSUE TITLE
Callback URL when the task is finish

### ISSUE THREAD

**Issue by ZulluBalti** [OpenDroneMap/NodeODM#203]
### What is the problem?

Currently, from looking at the documentation it looks like we have to wait for a task to finish before processing it. And sometimes it may take too long to finish. And the request may fail in some hosting services like vercel which only gives 10s on a free plan and 60s (or 30s) on a paid account to a function to finish.

### What should be the expected  behavior?

There should be a way to send a URL and when the task is completed it will call that url with required data (like UUID) etc.
This way we don't have to wait for the task to finish if it takes too long.

**Comment by pierotofy** [comment]
There already is, see the `--webhook` parameter when launching NodeODM: https://github.com/OpenDroneMap/NodeODM/blob/master/config.js#L48
