### ISSUE TITLE
How to maximize available nodes

### ISSUE THREAD

**Issue by husnimubarok** [OpenDroneMap/NodeODM#21]
I'm running three node (each 4 core and 8GB RAM). It seems the load was not distributed to all available nodes. Am I missing some configuration? 

![node-0](https://user-images.githubusercontent.com/860363/29121391-91cf4556-7d38-11e7-8249-d1badeb0f8b5.PNG)
![node-1](https://user-images.githubusercontent.com/860363/29121392-91d3b276-7d38-11e7-951d-b782967b4152.PNG)
![node-2](https://user-images.githubusercontent.com/860363/29121393-91f7d12e-7d38-11e7-8712-c748cff0a831.PNG)

**Comment by pierotofy** [comment]
Adding more processing nodes will allow you to run multiple jobs in parallel.

You will not be able to distribute a single job across multiple processing nodes. We are actively working to bring this feature to reality, but we're not there yet.

**Comment by pierotofy** [comment]
Horizontal scaling is now possible via ClusterODM https://github.com/OpenDroneMap/ClusterODM and via split-merge https://github.com/OpenDroneMap/ODM/pull/979

**Comment by smathermather** [comment]
I love when the older issues just disappear... .
