### ISSUE TITLE
nodeodm refuses to launch with undefined minimist module

### ISSUE THREAD

**Issue by kpoman** [OpenDroneMap/NodeODM#211]
### What is the problem?

nodeodm wont run. I do see this in the console, stating require is not defined

```
ode-odm-1  | /var/www/config.js:21
node-odm-1  | let argv = require('minimist')(process.argv.slice(2));
node-odm-1  |                               ^
node-odm-1  |
node-odm-1  | TypeError: require(...) is not a function
node-odm-1  |     at Object.<anonymous> (/var/www/config.js:21:31)
node-odm-1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
node-odm-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
node-odm-1  |     at Module.load (internal/modules/cjs/loader.js:950:32)
node-odm-1  |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
node-odm-1  |     at Module.require (internal/modules/cjs/loader.js:974:19)
node-odm-1  |     at require (internal/modules/cjs/helpers.js:101:18)
node-odm-1  |     at Object.<anonymous> (/var/www/index.js:21:16)
node-odm-1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
node-odm-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```
after changing 
`let argv = require('minimist')(process.argv.slice(2));`
to this
```
var minimist = require('minimist');
let argv = minimist(process.argv.slice(2));
```
problem persists saying minimist is not a function
### What should be the expected behavior?
should run the code
### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)
git from the latest version

**Comment by pierotofy** [comment]
Thanks for reporting this issue; I've tried to replicate this, but I can't seem to be able to:

```
docker pull opendronemap/nodeodm
docker run -ti --rm opendronemap/nodeodm
<application launches normally>
```

**Comment by kpoman** [comment]
kpoman@DESKTOP-3784MCR:/mnt/c/Users/kpoma/Dev/webodm/WebODM$ docker pull opendronemap/nodeodm
Using default tag: latest
^@latest: Pulling from opendronemap/nodeodm
Digest: sha256:54bee9764646dd02d33259b3a71233f56cd9fb25c66f32ba896f2572a302eb5e
Status: Image is up to date for opendronemap/nodeodm:latest
docker.io/opendronemap/nodeodm:latest

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview opendronemap/nodeodm
kpoman@DESKTOP-3784MCR:/mnt/c/Users/kpoma/Dev/webodm/WebODM$ docker run -ti --rm opendronemap/nodeodm
/var/www/config.js:21
let argv = require('minimist')(process.argv.slice(2));
                              ^

TypeError: require(...) is not a function
    at Object.<anonymous> (/var/www/config.js:21:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/var/www/index.js:21:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
kpoman@DESKTOP-3784MCR:/mnt/c/Users/kpoma/Dev/webodm/WebODM$

**Comment by kpoman** [comment]
btw I am trying this on Windows 10 via WSL + Ubuntu terminal

**Comment by kpoman** [comment]
I uninstalled windows docker, and installed the one provided with ubuntu with WSL (windows subsystem for linux), deleted and re-checked everything out, and it works on windows this way.

**Comment by pierotofy** [comment]
Oh, awesome.

If you think this was a problem with the installation of docker, feel free to close this issue?

**Comment by kpoman** [comment]
Well, maybe you want to validate that this works with windows docker instead of WSL docker, so feel free to investigate that alternative and if it is an unsupported platform (native docker for windows) we can close it. You tell me!

**Comment by pierotofy** [comment]
We can probably close it.
