### ISSUE TITLE
Unable to See Releases Tags in the github

### ISSUE THREAD

**Issue by usman-rind** [OpenDroneMap/NodeODM#212]
Docker hub released tags are not available in github
May be devops pipelines are not working correctly which are causing the issue of versions mismatch. 
Could you please check and respond?

it should be same at both ends. 

Just Check on https://hub.docker.com/r/opendronemap/nodeodm/tags  tags are available till 3.3.4 while on the the github https://github.com/OpenDroneMap/NodeODM/tags tags are available till 2.2.2.

**Comment by pierotofy** [comment]
We don't currently publish all releases on docker hub. Expect for the `latest` tag, don't rely on any other version published on docker hub.
