### ISSUE TITLE
 matcher-order setting doesn't have any effect

### ISSUE THREAD

**Issue by muratmaga** [OpenDroneMap/NodeODM#213]
We typically capture our image through a turntable, meaning that two sequential shots would have the most overlap. There is no GPS exif data. Filename formats are like image_0001.png, image_0002.png etc....

I set the matcher-order 100  to make sure matching is done through filenames. However, log file still shows random images being picked up for matching. Is there any other setting I need to set beyond this to make sure matcher-order is working correctly.

Thanks,

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
