### ISSUE TITLE
[INFO]    Using CPU for feature extraction: Cannot initialize CUDA

### ISSUE THREAD

**Issue by torsteinelv** [OpenDroneMap/NodeODM#224]
### What is the problem?

getting gpu support.

### What should be the expected behavior?

[Type answer here]

### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)

I have tried with different platforms and same issue is on all of them.

I dont see any gpu support and before starting a job I see in logs:
[INFO]    Using CPU for feature extraction: Cannot initialize CUDA

even i have nvidia driver active:
root@k8s-m1:~# kubectl exec -it nodeodm-0 -n opendronemap -- nvidia-smi
Tue Sep  3 14:43:17 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro P2000                   On  |   00000000:00:10.0 Off |                  N/A |
| 53%   48C    P8              5W /   75W |       2MiB /   5120MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
root@k8s-m1:~# 

Containers:
  nodeodm:
    Container ID:  containerd://195268e2e6c739fb9492d0f590cfbfe353a85fb9188bdbf9c8c1a98948567f0e
    Image:         opendronemap/nodeodm:gpu
    Image ID:      docker.io/opendronemap/nodeodm@sha256:b7c973d442a5e715c518f0029412f1647069f84dbc614673ff01b56698b562e3
    Port:          3000/TCP
    Host Port:     0/TCP
    Args:
      --gpus all
    State:          Running
      Started:      Tue, 03 Sep 2024 16:39:14 +0200
    Ready:          True
    Restart Count:  0
    Environment:
      NVIDIA_VISIBLE_DEVICES:  all
    Mounts:
      /cm/local from data-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ns528 (ro)

any suggestions on how to solve this?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
