### ISSUE TITLE
 All task files will be automatically cleaned, how to disable it

### ISSUE THREAD

**Issue by XiezhDev** [OpenDroneMap/NodeODM#229]
I am running it with docker. All files, including temporary files and generated files, will be automatically cleaned up after a few days. How can I disable this behavior?

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray: The forum is the right place to ask questions (we try to keep the GitHub issue tracker for feature requests and bugs only). Thank you! :+1:
