### ISSUE TITLE
Replace gdal2tiles.py with gdal2tiles_parallel.py

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/NodeODM#24]
Help speed up the last part of the process: https://github.com/GitHubRGI/geopackage-python/blob/master/Tiling/gdal2tiles_parallel.py

**Comment by giovannicimolin** [comment]
There's also this repo: https://github.com/pramsey/gdal2tilesp/

**Comment by pierotofy** [comment]
Very nice! Perhaps we could do a benchmark and choose the fastest between the two.

**Comment by pierotofy** [comment]
Another candidate: https://github.com/Luqqk/gdal2tiles

**Comment by giovannicimolin** [comment]
I found out that gdal2tiles.py already supports multicore tiling, but it's not released with GDAL on yet, it's only on their SVN trunk.

I've tested and found out it works really well and also better handles nodata values.

On their repo: https://svn.osgeo.org/gdal/trunk/gdal/swig/python/scripts/gdal2tiles.py

**Comment by smathermather** [comment]
@giovannicimolin -- do you have time to put together a pull request?

**Comment by giovannicimolin** [comment]
@smathermather We've dropped support for node-ODM and are currently using a custom solution based on OpenDroneMap.

**Comment by giovannicimolin** [comment]
@smathermather Not much right now, but when gdal releases their trunk version of gdal2tiles.py I can make a PR.

**Comment by pierotofy** [comment]
This has been taken care of.
