### ISSUE TITLE
CPU/Memory Usage

### ISSUE THREAD

**Issue by FLYBYME** [OpenDroneMap/NodeODM#3]
It would be nice to have a historical view on system usage.

**Comment by smathermather** [comment]
I expect we'll be building some of this into ODM with improvements to resource tracking upcoming in OpenSfM.

**Comment by pierotofy** [comment]
This was opened 3 years ago, but there hasn't been a push to implement it. There's also other tools, like Grafana https://play.grafana.org that would probably solve this need better. PRs are welcome if there's still interest.

**Comment by smathermather** [comment]
Yup. Agreed that 3rd party tools make sense here.
