### ISSUE TITLE
node-uuid depreciated error

### ISSUE THREAD

**Issue by PeterSprague** [OpenDroneMap/NodeODM#34]
$ npm install

npm install error:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/nodemon/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
Removing intermediate container 48d312d65960

npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated coffee-script@1.10.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global jshint@2.9.5 should be installed with -g

Revised node-uuid to uuid in package.json
$ npm install -g coffeescript jshint

docker run throws node-uuid missing error
added node-uuid with uuid, now runs

**Comment by pierotofy** [comment]
I'm a bit confused, could you explain in more detail what the problem is and steps to reproduce it?

**Comment by PeterSprague** [comment]
As you said, not directly breaking the build.  Wanted to tune now to remove the warnings and take care of lingering legacy code

To reproduce:
Revised node-uuid to uuid in package.json
$ npm install -g coffeescript jshint

$ docker build .....
$ docker run ......

**Comment by pierotofy** [comment]
I see! Would you be willing to open a PR with the changes to `package.json` and `Dockerfile` (if applicable)?

**Comment by PeterSprague** [comment]
Can do once have a solution
