### ISSUE TITLE
Cancelled does not kill process

### ISSUE THREAD

**Issue by FLYBYME** [OpenDroneMap/NodeODM#5]
When a task is cancelled the underlying process keeps living. We end up losing track of the process and all its logs even though its still running.

**Comment by pierotofy** [comment]
Yes this is an outstanding issue (I documented it in the source code) https://github.com/OpenDroneMap/node-OpenDroneMap/blob/master/libs/Task.js#L193

I wonder if sending a SIGTERM instead of SIGKILL would fix it, although ideally this should be fixed on OpenDroneMap.

**Comment by FLYBYME** [comment]
Im not sure what the best signal to send would be.
One thing I can say is this line:
https://github.com/OpenDroneMap/node-OpenDroneMap/blob/master/libs/Task.js#L199
We are wiping out any reference to the running processes by setting `this.runningProcesses = [];` 
The removing of the process object should be done in `handleProcessExit` using the splice function of the array. That way when node says the process has exited then we know its done and if no more processes are running then we can call `stopTrackingProcessingTime`

**Comment by pierotofy** [comment]
That sounds like a good approach. Would you be willing to make a pull request to address this problem? Otherwise I can try to take a stab at it sometimes in the next few days.

**Comment by FLYBYME** [comment]
Ill see what I can do. My ES6 is not so great.

**Comment by pierotofy** [comment]
ODM now handles SIGTERM signals much better, which should fix the problem that was reported here. If it's still a problem, please re-open it :clinking_glasses:
