### ISSUE TITLE
Add option to upload results to S3

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/NodeODM#52]
We should have a config to enable upload of complete results to S3.

**Comment by pierotofy** [comment]
This is now implemented in the `apichanges` branch. cc @talltom

**Comment by matthewberryman** [comment]
@pierotofy seems you forgot to push the apibranches branch? I can't find it in the list of [GH branches](https://github.com/OpenDroneMap/NodeODM/branches) at present time.

**Comment by smathermather** [comment]
https://github.com/pierotofy/node-OpenDroneMap/tree/apichanges

**Comment by smathermather** [comment]
@matthewberryman
