### ISSUE TITLE
Cannot access processing node after update

### ISSUE THREAD

**Issue by xmutantson** [OpenDroneMap/NodeODM#65]
There's no template here, so I'll try to get everything. I'm using WebODM on windows 10, version 0.7.0. Also using WebODM on 16.04 Ubuntu Linux LTS, as an easy way to interface with its processing node from windows. My issue is that with the latest upgrade, the processing node running on the Linux box on port 3000 has stopped responding. Manual starts and stops of WebODM has not resolved the issue. Here is my start script, which is in /etc/init.d

[code]
#!/bin/sh
cd /home/kameron/WebODM
./webodm.sh start
docker run -p 3000:3000 -v /mnt/sdb1:/var/www/data opendronemap/node-opendronemap
#docker run -p 3000:3000 opendronemap/node-opendronemap
[/code]

I have been successful at starting WebODM through the console with no errors, but the node isn't connecting over the network and looking through the start script, I think this is the best place to ask this.

**Comment by pierotofy** [comment]
If you run from a shell:

`docker run -p 3000:3000 -v /mnt/sdb1:/var/www/data opendronemap/node-opendronemap`

Are you able to access http://localhost:3000 ? If so, then the node is working fine. Note that you should use the IP address of your network card to reference the node in WebODM, don't set the hostname to `localhost`, use the IP address instead.

**Comment by xmutantson** [comment]
Here's the output. Not sure what to make of it. 

kameron@SilverPancake:~/WebODM$ docker run -p 3000:3000 -v /mnt/sdb1:/var/www/da                                             ta opendronemap/node-opendronemap
docker: Error response from daemon: driver failed programming external connectiv                                             ity on endpoint youthful_carson (09b9222a6afb134801e3ad2d64b76c4d1ca7130144f68b8                                             b583a402030a13cbc): Bind for 0.0.0.0:3000 failed: port is already allocated.
ERRO[0000] error getting events from daemon: net/http: request canceled
kameron@SilverPancake:~/WebODM$

**Comment by xmutantson** [comment]
So I think I now understand what you were asking me to do. I went to the address int he web browser. This is what I have. 
![image](https://user-images.githubusercontent.com/29498365/50414152-ba2ee580-07c8-11e9-838c-f1c641982ef8.png)

**Comment by xmutantson** [comment]
I tried it again, and now with new results. I am on a local netowrk with the server and now get this error. @pierotofy 
![image](https://user-images.githubusercontent.com/29498365/50733159-2d2b4b00-113d-11e9-8f8c-31ec655cf4e7.png)

**Comment by pierotofy** [comment]
@xmutantson I wish I knew what the problem was, but I don't know what's causing it. It seems to be specific to the environment in which you are running WebODM on, so it's likely a possible configuration/network issue, not necessarily a problem with WebODM itself?

**Comment by xmutantson** [comment]
[code]
Ping statistics for 192.168.8.112:
    Packets: Sent = 55, Received = 55, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 1ms, Average = 0ms
[/code]
How is this a network issue? My network seems stable to me. That ping report was generated after deleting webodm on both machiens and reinstalling. Is it significant that the API versions are different for the built in processing node versus the server's API version?

**Comment by pierotofy** [comment]
There's only one API, that's the NodeODM API (the latest version is 1.3.1). WebODM doesn't care too much about what version you are using, as the API as not changed much since its first release. If in doubt, make sure you are running the latest version of both software, but I don't think that's the root of the problem.

**Comment by pierotofy** [comment]
Closing as this does not seem a bug in NodeODM.
