### ISSUE TITLE
Split-merge Support

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/NodeODM#69]
We should expand the NodeODM API to support the split-merge workflow. Design to be decided. Possibly related/connected to https://github.com/MasseranoLabs/nodeodm-proxy/issues/4

**Comment by smathermather** [comment]
👍 cc @dakotabenjamin

**Comment by pierotofy** [comment]
Done via seed file support and partial output retrieval (1.5.0 spec changes).
