### ISSUE TITLE
I hope get tasks list by REST API

### ISSUE THREAD

**Issue by kladess** [OpenDroneMap/NodeODM#76]
I hope get tasks list by REST API

**Comment by pierotofy** [comment]
Hey @kladess can you explain more in details your use case?

Retrieving the task list would expose tasks processed by all users, which could be a problem in environments where multiple users are submitting tasks.

**Comment by kladess** [comment]
hi @pierotofy I agree to your mention, it will be make other problem.

I just hope checking NodeODM Status.
because not showing in Web UI when i command by api from c# or java

**Comment by pierotofy** [comment]
I would probably try to check the status directly from your Java or C# application. Keep track of the task ID and then query it at regular intervals for status updates?
