### ISSUE TITLE
[Improvement] Save settings file in all.zip

### ISSUE THREAD

**Issue by MatthiasSiewert** [OpenDroneMap/NodeODM#81]
Would be great to save the settings/options for processing as a simple text file in the all.zip that can be downloaded once processing is complete. This way it can be easily traced what settings worked well an which didn't.

**Comment by pierotofy** [comment]
Would a summary of the settings used in the console output of the task work also?

**Comment by MatthiasSiewert** [comment]
I am not sure what the console output would be, but what i would be interested in, as a user, are the changes compared to the default settings, something like the dashboard summary:
```

Created on: 5/14/2019, 5:15:34 PM

Processing Node: node-odm-1:3000 (auto)

Options: orthophoto-resolution: 5, fast-orthophoto: true, crop: 0, skip-3dmodel: true, use-hybrid-bundle-adjustment: true
```


My idea was to have a simple reminder to trace back what settings have been used to achieve a specific result.

**Comment by pierotofy** [comment]
I've added the config options to the output of the console log when running an ODM process in https://github.com/OpenDroneMap/ODM/pull/979/commits/ee188803053e7f1ec8408d5e8b24480ba327e241

So now people will be able to trace back the options by looking at the console output:

```
[INFO]    Initializing OpenDroneMap app - Sun May 19 19:31:47  2019
[DEBUG]   ==============
[DEBUG]   build_overviews: False
[DEBUG]   crop: 3
[DEBUG]   dem_decimation: 1
[DEBUG]   dem_euclidean_map: False
[DEBUG]   dem_gapfill_steps: 3
[DEBUG]   dem_resolution: 5
[DEBUG]   depthmap_resolution: 640
[DEBUG]   dsm: False
[DEBUG]   dtm: False
[DEBUG]   end_with: odm_orthophoto
...
```

This will become available when the split merge branch is merged (in the upcoming weeks).

Thanks for the feedback!!

**Comment by smathermather** [comment]
Absolutely awesome. This is always such a pain to reconstruct if one isn't incredibly organized.
