### ISSUE TITLE
How to get other output files in odm_orthophoto?

### ISSUE THREAD

**Issue by htlin** [OpenDroneMap/NodeODM#83]
https://github.com/OpenDroneMap/NodeODM/blob/434b84bf7c2a8e618ed25bbff13d786fd3121a62/libs/Task.js#L341
In this line I see that this is the default list of outputs to be compressed as "All Assets", however it is missing some other files such as `odm_orthophoto/odm_orthophoto_corners.txt` and `odm_orthophoto/odm_orthophoto_log.txt`.

Is there a way to specify this outputs list somewhere?

**Comment by pierotofy** [comment]
Yes, you can use the `outputs` field in https://github.com/OpenDroneMap/NodeODM/blob/master/docs/index.adoc#post-tasknew

In PyODM this is available via `create_task` (`outputs` parameter): https://pyodm.readthedocs.io/en/latest/#api
