### ISSUE TITLE
Troubles to run NodeODM node

### ISSUE THREAD

**Issue by adamavip** [OpenDroneMap/NodeODM#90]
Hello,

I have an issue and any help would be welcome. When i am trying to run the command docker run -ti -p 3000:3000 opendronemap/nodeodm. It seems that it connects to the server. The output is:
 info: Authentication using NoTokenRequired
info: Listening on 0.0.0.0:6367 UDP for progress updates
info: No tasks dump found
info: Checking for orphaned directories to be removed...
info: Server has started on port 3000

but when i enter localhost:3000 in a web browser i don't observe anything. 

I would be grateful to anyone for any help. It's urgent

**Comment by pierotofy** [comment]
Hey @adamavip, could we move over the conversation to https://community.opendronemap.org? This looks like it's a configuration/network problem, not a bug.

Thank you! :pray:
