### ISSUE TITLE
Max images where to Config??

### ISSUE THREAD

**Issue by yingyi-ma** [OpenDroneMap/NodeODM#92]
![image](https://user-images.githubusercontent.com/49050636/61856596-096efd00-aef5-11e9-8792-3d0ba894b36d.png)

**Comment by pierotofy** [comment]
Hey @yingyi-ma  :hand: this looks like a question, can we move the discussion to https://community.opendronemap.org  (this issue tracker is for reporting bugs) ?

Thank you!
