### ISSUE TITLE
Save copy of input parameters as JSON for each dataset

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/NodeODM#96]
It could be useful to know which parameters were used and how to reprocess a dataset.

**Comment by Saijin-Naib** [comment]
In addition to what Piero wrote above, I believe the below workflow is a compelling use-case for this project JSON.

If in the future the infrastructure is modified to accommodate it, having this project source JSON would also enable workflows similar to Pix4D where a project can be begun locally and then migrated to the cloud or another processing node, or vice-versa (a workflow I made heavy use of prior).

It could potentially also serve as a baseline set of parameters or products, greatly easing the production of datasets and ensuring consistency between projects.

**Comment by pierotofy** [comment]
Closed by https://github.com/OpenDroneMap/ODM/pull/1297
